### ISSUE TITLE
Xalan dependency broke maven-bundle-plugin

### ISSUE THREAD

**Issue by amarkevich** [ipastusi/wiremock-maven-plugin#110]
version 4.4.1+ with Xalan dependency included (#41) cause  maven-bundle-plugin failure [1]

[pom.xml.txt](https://github.com/automatictester/wiremock-maven-plugin/files/4388481/pom.xml.txt)

1. Exception in thread "main" javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
        at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:177)
        at java.xml/javax.xml.transform.FactoryFinder.find(FactoryFinder.java:212)
        at java.xml/javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:126)
        at org.apache.felix.bundleplugin.BlueprintPlugin.getTransformer(BlueprintPlugin.java:384)
        at org.apache.felix.bundleplugin.BlueprintPlugin.<init>(BlueprintPlugin.java:67)
        at aQute.bnd.osgi.Processor.loadPlugin(Processor.java:820)
        at aQute.bnd.osgi.Processor.loadPlugins(Processor.java:653)
        at aQute.bnd.osgi.Processor.getPlugins(Processor.java:575)
        at aQute.bnd.osgi.Processor.getPlugins(Processor.java:516)
        at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:874)
        at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:239)
        at aQute.bnd.osgi.Builder.analyze(Builder.java:408)
        at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:909)
        at aQute.bnd.osgi.Builder.build(Builder.java:118)
        at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:940)
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:443)
        at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:364)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: org/apache/xalan/processor/TransformerFactoryImpl
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.xml/javax.xml.transform.FactoryFinder.getProviderClass(FactoryFinder.java:122)
        at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:165)
        ... 38 more

**Comment by automatictester** [comment]
Hi, many thanks for this issue report. As you have noticed, I bundled `xalan` dependency in #41 in order to resolve `saxon` problem. At that time I wasn't aware of any side effects, as the one you have reported. If I would know about that at that time, I'd probably not add `xalan` to the plugin dependencies, but let the affected users add it themselves to `//plugin/dependencies`, on the same level where we have `wiremock` itself since version 5.0.0 of this plugin. Having said that, I am now reluctant to revert that, as it would bring instability to the existing users. However, I can see a simple solution for your case - add `xalan` as a dependency for `maven-bundle-plugin`:

```
         <plugin>
            <groupId>org.apache.felix</groupId>
            <artifactId>maven-bundle-plugin</artifactId>
            <version>4.2.1</version>
            <extensions>true</extensions>
            <dependencies>
               <dependency>
                  <groupId>xalan</groupId>
                  <artifactId>xalan</artifactId>
                  <version>2.7.2</version>
               </dependency>
            </dependencies>
         </plugin>
```

Could you please let me know if it resolves your problem? Other than that, if you have a better solution in mind, or would like to open a PR, you are welcome.

**Comment by automatictester** [comment]
Closing due inactivity. Solution stated above.
